= The dotnet mono repository for me
Shuai Zhang<zhangshuai.ustc@gmail.com>
v1.1, 2022-08-11

OneDotNet is a mono-repo for all of my DotNet codes. Please check Google's article link:https://cacm.acm.org/magazines/2016/7/204032-why-google-stores-billions-of-lines-of-code-in-a-single-repository/fulltext[Why Google Stores Billions of Lines of Code in a Single Repository] for more details about why this repo born.

Bazel currently has poorly support for DotNet projects. Just put all DotNet projects here.

== Getting Started

=== Prerequisites

Install VS2022 (optional) & .NET 6.0 for compilation & runtime.

=== Compile

[source]
----
dotnet build dirs.proj
----

=== SlnGen

See link:https://microsoft.github.io/slngen/[SlnGen] & link:https://github.com/microsoft/vssetup.powershell[VSSetup].

[source,PowerShell]
----
slngen -vs ((Get-VSSetupInstance).InstallationPath + "\Common7\IDE\devenv.exe") --folders true --collapsefolders true -o OneDotNet.sln
----

=== Pack

Add `/p:PublicRelease=true /p:ContinuousIntegrationBuild=true` for formal packaging.

[source]
----
dotnet pack <project_path> -c Release
----

== Deprecated Packages

These packages are deprecated and source code removed. The link can redirect you to the last commit before removing it.

* link:https://github.com/hcoona/OneDotNet/tree/7cc2064/srcs/public/Clocks.Net[Clocks.Net].
  This package is superseded by .NET 8.0 native API link:https://learn.microsoft.com/en-us/dotnet/api/system.timeprovider?view=net-8.0[TimeProvider] or backport package link:https://www.nuget.org/packages/Microsoft.Bcl.TimeProvider/[Microsoft.Bcl.TimeProvider].
* link:https://github.com/hcoona/OneDotNet/tree/5ab8904/TimeLimiter[TimeLimiter].
  This package is ill-designed & has performance issue. Please do not use it.
* link:https://github.com/hcoona/OneDotNet/tree/b687bee/SwigDoc2Latex[SwigDoc2Latex].
  Converting link:https://www.swig.org/[SWIG(Simplified Wrapper and Interface Generator)] documents to LaTeX format. This application is unmaintained & may not work due to website changing.
* link:https://github.com/hcoona/OneDotNet/tree/73a338a/GeothermalResearchInstitute[GeothermalResearchInstitute].
  This is a part-time work for Geothermal Research Institute. Didn't maintain.
* link:https://github.com/hcoona/OneDotNet/tree/7b14411/GrpcAdapter[HCOONa.Grpc.MicrosoftExtension.Logging].
  Deprecate this package due to `Grpc.Core` is deprecated. See link:https://github.com/grpc/grpc/tree/v1.49.1/src/csharp/README.md[gRPC C# README.md] for further details.
