trigger: none

pr: none

pool:
  vmImage: 'windows-latest'

variables:
  osSuffix: 'windows'
  isWindows: true
  buildConfiguration: 'Release'
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages

steps:
- template: /.azure-pipelines/common/build.yml@self
  parameters:
    isOfficial: 'false'
    packProjects: 'true'
    projects: 'srcs/public/Clocks.Net/dirs.proj'

- template: /.azure-pipelines/common/publish.yml@self
  parameters:
    isOfficial: 'false'
    tagPrefix: 'Clocks.Net'
