trigger: none

pool:
  vmImage: 'windows-latest'

variables:
  osSuffix: 'windows'
  isWindows: true
  buildConfiguration: 'Release'
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages

steps:
- script: exit 1
  condition: ne(variables['Build.SourceBranch'], 'refs/heads/main')
- template: /.azure-pipelines/build.yml@self
  parameters:
    isOfficial: 'false'
    packProjects: 'true'
